version: "3"

services:
  rabbitmq-container:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=api-db
    restart: always

  app-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/testdb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_RABBITMQ_HOST=rabbitmq-container
    depends_on:
      - rabbitmq-container
      - db
